{
 "title": "Google-Monetize - Ad Performance Dashboard",
 "tags": [
  "gm",
  "adscenter",
  "performance"
 ],
 "refresh": "1m",
 "panels": [
  {
   "title": "Global Click-Through Rate (CTR)",
   "type": "singlestat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "format": "percentunit",
   "targets": [
    {
     "metricQuery": {
      "query": "fetch cloud_run_revision | { metric 'prometheus.googleapis.com/gm_adscenter_ad_clicks_total/counter' ; metric 'prometheus.googleapis.com/gm_adscenter_ad_impressions_total/counter' } | ratio | group_by [], [value: aggregate(value)]"
     }
    }
   ]
  },
  {
   "title": "Global Conversion Rate (CVR)",
   "type": "singlestat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "format": "percentunit",
   "targets": [
    {
     "metricQuery": {
      "query": "fetch cloud_run_revision | { metric 'prometheus.googleapis.com/gm_adscenter_ad_conversions_total/counter' ; metric 'prometheus.googleapis.com/gm_adscenter_ad_clicks_total/counter' } | ratio | group_by [], [value: aggregate(value)]"
     }
    }
   ]
  },
  {
   "title": "Total Ad Impressions",
   "type": "singlestat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "format": "short",
   "targets": [
    {
     "metricQuery": {
      "query": "fetch cloud_run_revision | metric 'prometheus.googleapis.com/gm_adscenter_ad_impressions_total/counter' | group_by [], [value: aggregate(value.gm_adscenter_ad_impressions_total)]"
     }
    }
   ]
  },
  {
   "title": "Active Ads",
   "type": "singlestat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "format": "short",
   "targets": [
    {
     "metricQuery": {
      "query": "fetch cloud_run_revision | metric 'prometheus.googleapis.com/gm_adscenter_ads_active/gauge' | group_by [], [value: aggregate(value.gm_adscenter_ads_active)]"
     }
    }
   ]
  },
  {
   "title": "CTR by Platform",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "CTR" }
   ],
   "targets": [
    {
     "metricQuery": {
      "query": "fetch cloud_run_revision | { metric 'prometheus.googleapis.com/gm_adscenter_ad_clicks_total/counter' ; metric 'prometheus.googleapis.com/gm_adscenter_ad_impressions_total/counter' } | ratio | group_by 1m, [platform], [value: aggregate(value)] | every 1m"
     }
    }
   ]
  },
  {
   "title": "Impressions by Platform",
   "type": "graph",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "metricQuery": {
      "query": "fetch cloud_run_revision | metric 'prometheus.googleapis.com/gm_adscenter_ad_impressions_total/counter' | group_by 1m, [platform], [value: aggregate(value.gm_adscenter_ad_impressions_total)] | every 1m"
     }
    }
   ]
  },
  {
   "title": "Top 10 Campaigns by CTR",
   "type": "table",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "metricQuery": {
      "query": "fetch cloud_run_revision | { metric 'prometheus.googleapis.com/gm_adscenter_ad_clicks_total/counter' ; metric 'prometheus.googleapis.com/gm_adscenter_ad_impressions_total/counter' } | ratio | group_by 1m, [campaign_id], [value: aggregate(value)] | every 1m | top 10"
     }
    }
   ]
  },
  {
   "title": "Platform Distribution (Impressions)",
   "type": "piechart",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "metricQuery": {
      "query": "fetch cloud_run_revision | metric 'prometheus.googleapis.com/gm_adscenter_ad_impressions_total/counter' | group_by [platform], [value: aggregate(value.gm_adscenter_ad_impressions_total)]"
     }
    }
   ]
  },
  {
   "title": "Cost Per Click (CPC) by Platform",
   "type": "graph",
   "gridPos": { "x": 0, "y": 20, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short", "label": "CPC (cents)" }
   ],
   "targets": [
    {
     "metricQuery": {
      "query": "fetch cloud_run_revision | { metric 'prometheus.googleapis.com/gm_adscenter_ad_spend_total/counter' ; metric 'prometheus.googleapis.com/gm_adscenter_ad_clicks_total/counter' } | ratio | group_by 1m, [platform], [value: aggregate(value)] | every 1m"
     }
    }
   ]
  },
  {
   "title": "Total Ad Spend by Platform",
   "type": "graph",
   "gridPos": { "x": 12, "y": 20, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short", "label": "Spend (cents)" }
   ],
   "targets": [
    {
     "metricQuery": {
      "query": "fetch cloud_run_revision | metric 'prometheus.googleapis.com/gm_adscenter_ad_spend_total/counter' | group_by 1m, [platform], [value: aggregate(value.gm_adscenter_ad_spend_total)] | every 1m"
     }
    }
   ]
  }
 ]
}