steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f','services/adscenter/Dockerfile','-t','asia-northeast1-docker.pkg.dev/${GCP_PROJECT_ID}/gm-services/adscenter:latest','.']
images: ['asia-northeast1-docker.pkg.dev/${GCP_PROJECT_ID}/gm-services/adscenter:latest']
